version: '3.9'
services:
  hydro:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - influxdb
      - mqtt
    ports:
      - "9000:9000"
    environment:
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN={$INFLUXDB_TOKEN}
      - INFLUX_ORG=kara
      - INFLUX_BUCKET=hydro
      - MQTT_BROKER=tcp://mqtt:1883
      - LOG_LEVEL=debug
    volumes:
      - ./data:/var/data

  mqtt:
    image: emqx/nanomq:latest
    ports:
      - '1883:1883'
      - '8883:8883'
    volumes:
      - ./configs/nanomq.conf:/etc/nanomq.conf

  influxdb:
    image: influxdb:latest
    volumes:
      - ./data/influx:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN={$INFLUXDB_TOKEN}
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=kara
      - DOCKER_INFLUXDB_INIT_RETENTION=2w
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_BUCKET=hydro
    ports:
      - '8086:8086'